name: Build and publish macOS aarch64 release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      os: macos-15
      upload-artifacts: true
      maven-prepare-args: install -DskipTests -f dependencies/install-jars/pom.xml
      maven-args: install -DskipTests -Djavafx.platform=mac-aarch64 -pl phoebus-product-display -am
      product-directory: phoebus-product-display

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        pattern: Phoebus product macos-15
        path: dist
    - name: Upload assets to GitHub Release
      run: find dist -type f \( -name '*.zip' -o -name '*.tar.gz' \) -exec gh release upload "$RELEASE_TAG" '{}' --clobber \;
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
        RELEASE_TAG: ${{ github.event.release.tag_name }}
